version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${APP_BIND:-127.0.0.1:8000}:8000
    expose:
      - 8000

  db:
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_BIND:-127.0.0.1:5432}:5432
    env_file:
      - .env
